name: Events
version: ${project.version}
main: fr.iban.events.EventsPlugin
api-version: 1.18
depend: [ Core ]
softdepend:
  - IceRace
authors: [ Iban ]
description: Plugin d'events

commands:
  event:
  host:
